# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/yuepi/ROBOCON_ARM/robo_arm

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/yuepi/ROBOCON_ARM/robo_arm

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/yuepi/ROBOCON_ARM/robo_arm/CMakeFiles /home/yuepi/ROBOCON_ARM/robo_arm//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/yuepi/ROBOCON_ARM/robo_arm/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

arm_sim.o: arm_sim.cpp.o
.PHONY : arm_sim.o

# target to build an object file
arm_sim.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/arm_sim.cpp.o
.PHONY : arm_sim.cpp.o

arm_sim.i: arm_sim.cpp.i
.PHONY : arm_sim.i

# target to preprocess a source file
arm_sim.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/arm_sim.cpp.i
.PHONY : arm_sim.cpp.i

arm_sim.s: arm_sim.cpp.s
.PHONY : arm_sim.s

# target to generate assembly for a file
arm_sim.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/arm_sim.cpp.s
.PHONY : arm_sim.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.s
.PHONY : main.cpp.s

rpi_serial.o: rpi_serial.cpp.o
.PHONY : rpi_serial.o

# target to build an object file
rpi_serial.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/rpi_serial.cpp.o
.PHONY : rpi_serial.cpp.o

rpi_serial.i: rpi_serial.cpp.i
.PHONY : rpi_serial.i

# target to preprocess a source file
rpi_serial.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/rpi_serial.cpp.i
.PHONY : rpi_serial.cpp.i

rpi_serial.s: rpi_serial.cpp.s
.PHONY : rpi_serial.s

# target to generate assembly for a file
rpi_serial.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/rpi_serial.cpp.s
.PHONY : rpi_serial.cpp.s

serial.o: serial.cpp.o
.PHONY : serial.o

# target to build an object file
serial.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/serial.cpp.o
.PHONY : serial.cpp.o

serial.i: serial.cpp.i
.PHONY : serial.i

# target to preprocess a source file
serial.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/serial.cpp.i
.PHONY : serial.cpp.i

serial.s: serial.cpp.s
.PHONY : serial.s

# target to generate assembly for a file
serial.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/serial.cpp.s
.PHONY : serial.cpp.s

servo.o: servo.cpp.o
.PHONY : servo.o

# target to build an object file
servo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/servo.cpp.o
.PHONY : servo.cpp.o

servo.i: servo.cpp.i
.PHONY : servo.i

# target to preprocess a source file
servo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/servo.cpp.i
.PHONY : servo.cpp.i

servo.s: servo.cpp.s
.PHONY : servo.s

# target to generate assembly for a file
servo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/servo.cpp.s
.PHONY : servo.cpp.s

tcpServer.o: tcpServer.cpp.o
.PHONY : tcpServer.o

# target to build an object file
tcpServer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/tcpServer.cpp.o
.PHONY : tcpServer.cpp.o

tcpServer.i: tcpServer.cpp.i
.PHONY : tcpServer.i

# target to preprocess a source file
tcpServer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/tcpServer.cpp.i
.PHONY : tcpServer.cpp.i

tcpServer.s: tcpServer.cpp.s
.PHONY : tcpServer.s

# target to generate assembly for a file
tcpServer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/tcpServer.cpp.s
.PHONY : tcpServer.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... main"
	@echo "... arm_sim.o"
	@echo "... arm_sim.i"
	@echo "... arm_sim.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... rpi_serial.o"
	@echo "... rpi_serial.i"
	@echo "... rpi_serial.s"
	@echo "... serial.o"
	@echo "... serial.i"
	@echo "... serial.s"
	@echo "... servo.o"
	@echo "... servo.i"
	@echo "... servo.s"
	@echo "... tcpServer.o"
	@echo "... tcpServer.i"
	@echo "... tcpServer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

